import { WidgetDefinition } from '../../models/dashboard';
import { SystemKpiCard } from './widgets/system-kpi-card/system-kpi-card';
import { SystemStatusChart } from './widgets/system-status-chart/system-status-chart';
import { SystemRecentTenants } from './widgets/system-recent-tenants/system-recent-tenants';
import { SystemGrowthChart } from './widgets/system-growth-chart/system-growth-chart';

export const SYSTEM_WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    id: 'sys-companies',
    label: 'Total Companies',
    icon: 'business',
    description: 'Total registered tenants.',
    category: 'kpi',
    content: SystemKpiCard,
    inputs: { kpiType: 'totalCompanies' },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'sys-active',
    label: 'Active Companies',
    icon: 'check_circle',
    description: 'Currently active tenants.',
    category: 'kpi',
    content: SystemKpiCard,
    inputs: { kpiType: 'activeCompanies' },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'sys-inactive',
    label: 'Inactive Companies',
    icon: 'warning',
    description: 'Suspended or deactivated tenants.',
    category: 'kpi',
    content: SystemKpiCard,
    inputs: { kpiType: 'inactiveCompanies' },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'sys-users',
    label: 'Total Users',
    icon: 'people',
    description: 'Users across all companies.',
    category: 'kpi',
    content: SystemKpiCard,
    inputs: { kpiType: 'totalUsers' },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'sys-status-chart',
    label: 'Tenant Status',
    icon: 'donut_large',
    description: 'Overview of tenant activation status.',
    category: 'charts',
    content: SystemStatusChart,
    defaultColumns: 1,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
  {
    id: 'sys-growth-chart',
    label: 'Tenant Growth',
    icon: 'show_chart',
    description: 'Tenant registrations over time.',
    category: 'charts',
    content: SystemGrowthChart,
    defaultColumns: 3,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 4,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
  {
    id: 'sys-recent-tenants',
    label: 'Recent Tenants',
    icon: 'history',
    description: 'Most recently registered companies.',
    category: 'lists',
    content: SystemRecentTenants,
    defaultColumns: 4,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 4,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  }
];


