import { WidgetDefinition } from '../../models/dashboard';
import { KpiCard } from './widgets/kpi-card/kpi-card';
import { RevenueChart } from './widgets/revenue-chart/revenue-chart';
import { StockHealth } from './widgets/stock-health/stock-health';
import { RecentOrders } from './widgets/recent-orders/recent-orders';
import { LowStock } from './widgets/low-stock/low-stock';
import { RecentActivities } from './widgets/recent-activities/recent-activities';

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  // ── KPI widgets (1x1 default) ──────────────────────────────────
  {
    id: 'kpi-revenue',
    label: 'Revenue',
    icon: 'payments',
    description: 'Total sales revenue generated in the selected period.',
    category: 'kpi',
    content: KpiCard,
    inputs: { kpiType: 'revenue' },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'kpi-orders',
    label: 'Products Sold',
    icon: 'shopping_cart',
    description: 'Number of products sold in the selected period.',
    category: 'kpi',
    content: KpiCard,
    inputs: { kpiType: 'orders' },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'kpi-profit',
    label: 'Total Profit',
    icon: 'account_balance_wallet',
    description: 'Net profit generated in the selected period.',
    category: 'kpi',
    content: KpiCard,
    inputs: { kpiType: 'profit' },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'kpi-low-stock',
    label: 'Out of Stock',
    icon: 'warning',
    description: 'Number of SKUs currently below minimum stock threshold.',
    category: 'kpi',
    content: KpiCard,
    inputs: { kpiType: 'low-stock' },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },

  // ── Charts ───────────────────────────────────────────────────────
  {
    id: 'revenue-chart',
    label: 'Sales Trend',
    icon: 'show_chart',
    description: 'Sales revenue & order volume graph over the last 7 days.',
    category: 'charts',
    content: RevenueChart,
    defaultColumns: 2,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 4,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
  {
    id: 'stock-health',
    label: 'Sales by Category',
    icon: 'bar_chart',
    description: 'Total sales revenue broken down by product category.',
    category: 'charts',
    content: StockHealth,
    defaultColumns: 1,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },

  // ── Tables & Lists ─────────────────────────────────────────────
  {
    id: 'top-products',
    label: 'Top Products',
    icon: 'star',
    description: 'Best performing products by revenue in the selected period.',
    category: 'tables',
    content: RecentOrders,
    defaultColumns: 2,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 4,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
  {
    id: 'low-stock',
    label: 'Reorder Now',
    icon: 'report_problem',
    description: 'SKUs requiring purchase order creation immediately.',
    category: 'lists',
    content: LowStock,
    defaultColumns: 1,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
  {
    id: 'recent-activities',
    label: 'Recent Activities',
    icon: 'notifications',
    description: 'A timeline of the most recent system activities.',
    category: 'lists',
    content: RecentActivities,
    defaultColumns: 1,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
];
