import { WidgetDefinition } from '../../models/dashboard';
import { KpiCard } from './widgets/kpi-card/kpi-card';
import { RevenueChart } from './widgets/revenue-chart/revenue-chart';
import { StockHealth } from './widgets/stock-health/stock-health';
import { RecentOrders } from './widgets/recent-orders/recent-orders';
import { LowStock } from './widgets/low-stock/low-stock';
import { RecentActivities } from './widgets/recent-activities/recent-activities';
import { DASHBOARD_KPIS } from './dashboard-data';

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  // ── KPI widgets (1x1 default) ──────────────────────────────────
  {
    id: 'kpi-revenue',
    label: 'Revenue (7d)',
    icon: 'payments',
    description: 'Total sales revenue generated in the last 7 days.',
    category: 'kpi',
    content: KpiCard,
    inputs: { kpi: DASHBOARD_KPIS[0] },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'kpi-orders',
    label: 'Orders (7d)',
    icon: 'shopping_cart',
    description: 'Number of orders placed in the last 7 days.',
    category: 'kpi',
    content: KpiCard,
    inputs: { kpi: DASHBOARD_KPIS[1] },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'kpi-inventory-value',
    label: 'Inventory Value',
    icon: 'inventory_2',
    description: 'Current monetary value of all stock on hand.',
    category: 'kpi',
    content: KpiCard,
    inputs: { kpi: DASHBOARD_KPIS[2] },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },
  {
    id: 'kpi-low-stock',
    label: 'Low Stock SKUs',
    icon: 'warning',
    description: 'Number of SKUs currently below reorder threshold.',
    category: 'kpi',
    content: KpiCard,
    inputs: { kpi: DASHBOARD_KPIS[3] },
    defaultColumns: 1,
    defaultRows: 1,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 2,
    defaultVisible: true,
  },

  // ── Charts ───────────────────────────────────────────────────────
  {
    id: 'revenue-chart',
    label: 'Sales Trend',
    icon: 'show_chart',
    description: 'Sales revenue & order volume graph over the last 7 days.',
    category: 'charts',
    content: RevenueChart,
    defaultColumns: 2,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 4,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
  {
    id: 'stock-health',
    label: 'Stock Health',
    icon: 'bar_chart',
    description: 'Stock level percentage by category vs reorder capacity.',
    category: 'charts',
    content: StockHealth,
    defaultColumns: 1,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },

  // ── Tables & Lists ─────────────────────────────────────────────
  {
    id: 'recent-orders',
    label: 'Recent Orders',
    icon: 'receipt_long',
    description: 'Latest sales order transactions with status and totals.',
    category: 'tables',
    content: RecentOrders,
    defaultColumns: 2,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 4,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
  {
    id: 'low-stock',
    label: 'Reorder Now',
    icon: 'report_problem',
    description: 'SKUs requiring purchase order creation immediately.',
    category: 'lists',
    content: LowStock,
    defaultColumns: 1,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
  {
    id: 'recent-activities',
    label: 'Recent Activities',
    icon: 'history',
    description: 'Real-time audit log of inventory & order events.',
    category: 'lists',
    content: RecentActivities,
    defaultColumns: 1,
    defaultRows: 2,
    minColumns: 1,
    maxColumns: 2,
    minRows: 1,
    maxRows: 3,
    defaultVisible: true,
  },
];
